Update constants.js, make them correct for 2023-24 academic year
WilliamsStudentsOnline/wso-react pull request #249
Opened 2023-08-22 21:44 UTC by ssocolow

2023-08-22 21:45 UTC, ssocolow commented
This will fix the add to gcal button, which right now puts your classes in your calendar but one year ago.

2023-08-30 09:02 UTC, AndrewMuh requested changes

2023-08-30 09:02 UTC, AndrewMuh commented on src/constants/constants.js
> +    START: "20230131",
```suggestion
    START: "20240131",
```

2023-08-30 09:02 UTC, AndrewMuh commented on src/constants/constants.js
>    Winter: {
Please fix all the dates

2023-08-30 16:09 UTC, ssocolow commented on src/constants/constants.js
>    Winter: {
Should be done now

2023-09-04 03:07 UTC, AndrewMuh approved these changes
LGTM

2023-09-04 03:34 UTC, yechs approved these changes

2023-09-04 03:34 UTC, yechs commented on src/constants/constants.js
> +    FALL: "2024-04-24",
This should be something like 2023-04-26. I can change it after merging.

2023-09-04 03:38 UTC, merged