add query builder
WilliamsStudentsOnline/wso-react pull request #294
Opened 2024-01-17 15:51 UTC by asashepard

2024-01-18 16:37 UTC, AndrewMuh requested changes
Make code more readable and break things into smaller components/functions. Rerequest me when done.

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +  const [button1, setButton1] = useState(false);
what is button1-7? Fix naming to like professorFilterSelected, right now this makes the code very difficult to understand

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +  function handleClick() {
Change to `const handleClick = () => {}` instead of using function keyword. Do this for all functions.

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +  const [selected, setSelected] = useState(false);
rename selected to something that more closely identifies what's selected

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +      str += prior ? " AND (" : "(";
You can use format string for cleaner building.

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +    if (name.trim() !== "") {
break each one of these out to it's own function. This function is too long

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +  function QueryManager() {
I would actually make query manager its own component and just use it in the homepage.

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/Homepage.tsx
> +                        <option value=""></option>
This should break out to it's own helper function.

2024-01-18 16:37 UTC, AndrewMuh commented on src/components/views/Facebook/FacebookLayout.tsx
Why is the code form homepage all here? If you find yourself duplicating code like this, you should definitely be breaking stuff into its own components.

2024-02-01 22:32 UTC, yechs commented
Resolves #172

2024-02-01 22:50 UTC, yechs requested changes
Some of the feedback was given synchronously during the dev session.

TL;DR
- [ ] state management without duplication
- [ ] automatic class year calculation (no hardcoded class years)

2024-02-01 22:50 UTC, yechs commented on src/components/Homepage.tsx
> +  const [year24Selected, setYear24Selected] = useState(false);
The years can be autogenerated. These states should be interpreted as first-years/sophomores/juniors/seniors, and then added by the base academic year.

The academic year can be calculated with these codes here. We may want to turn it into a util function for reuse.

https://github.com/WilliamsStudentsOnline/wso-react/blob/d82b8cee4f4442373459dbdc01f8d4ced20e845c/src/constants/constants.js#L25-L31

2024-02-01 22:50 UTC, yechs commented on src/components/Homepage.tsx
>    const [query, updateQuery] = useState("");
This is an interesting design. However, I think `query` and `search` can be merged as one, where updates directly shows up in the query box.

That being said, we can offer user a separate textbox in the advanced search options.

Think of the "all these words: " box in [Google's Advanced Search page](https://www.google.com/advanced_search).

2024-02-01 22:50 UTC, yechs commented on src/components/QueryManager.jsx
> +  }
As in previous comment, turn the state into a mathematical term to be added to the base academic year.

2024-02-01 22:50 UTC, yechs commented on src/components/Homepage.tsx
> +  const [year24Selected, setYear24Selected] = useState(false);
Also, the state here could simply be a number, or an enum of four options (preferred) if you want.

2024-02-01 22:50 UTC, yechs commented on src/components/views/Facebook/FacebookLayout.tsx
> +  const [building, updateBuilding] = useState("");
Having these states stored duplicated at two places doesn't seem ideal.

We can maybe use a global state (like a redux slice that isn't persisted), or manually pass these down as props (would be a lot of painful work IMO)

 @AndrewMuh thoughts?

2025-04-28 00:08 UTC, charlietharas commented
TODO:
- update branch
- visual improvements

2025-04-28 02:48 UTC, merged